### ISSUE TITLE
Ubuntu Quick Start Errors

### ISSUE THREAD

**Issue by mcgrews3** [DynomiteDB/DynomiteDB.github.io#1]
http://www.dynomitedb.com/docs/dynomite/v0.5.8/quick-start-ubuntu/

Are these instructions still valid?  Is apt.dynomitedb.com working?

Using ubuntu 14.04 and apt-get to download and install dynomitedb.  When running apt-get i get a long pause when it reaches the apt.dynomitedb.com repository.  It then ends up ignoring the dynomitedb repository:

```
Ign https://apt.dynomitedb.com trusty InRelease                                
Ign https://apt.dynomitedb.com trusty Release.gpg
Ign https://apt.dynomitedb.com trusty Release
```

After a further long pause I get these error messages: 

```
Err https://apt.dynomitedb.com trusty/main amd64 Packages
  gnutls_handshake() failed: A TLS packet with unexpected length was received.
Err https://apt.dynomitedb.com trusty/main i386 Packages
  gnutls_handshake() failed: A TLS packet with unexpected length was received.
W: Failed to fetch https://apt.dynomitedb.com/dists/trusty/main/binary-amd64/Packages  gnutls_handshake() failed: A TLS packet with unexpected length was received.

W: Failed to fetch https://apt.dynomitedb.com/dists/trusty/main/binary-i386/Packages  gnutls_handshake() failed: A TLS packet with unexpected length was received.

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Have done what I can to rule out the configuration of the Ubuntu host etc as the root cause.

I did a ap-get with print-utis flag to get the following:

```
'https://apt.dynomitedb.com/dists/trusty/main/binary-amd64/Packages.bz2' apt.dynomitedb.com_dists_trusty_main_binary-amd64_Packages 0 :
'https://apt.dynomitedb.com/dists/trusty/main/binary-i386/Packages.bz2' apt.dynomitedb.com_dists_trusty_main_binary-i386_Packages 0 :
'https://apt.dynomitedb.com/dists/trusty/InRelease' apt.dynomitedb.com_dists_trusty_InRelease 0 
``` 

I try to access these uris in my web browser and get HTTP 503 responses.

When I try to curl https://apt.dynomitedb.com I get

```
curl -k https://apt.dynomitedb.com
curl: (35) Server aborted the SSL handshake
```

**Comment by akbarahmed** [comment]
@mcgrews3 Please use the Netflix (upstream) repos https://github.com/Netflix/dynomite 

The apt build is out of date and we took down the apt repo to prevent people from using an old build.

I'll update the docs and README etc. to reflect this.

**Comment by mcgrews3** [comment]
Thank you.
